language: python
python:
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - pytest overwatch-py/tests.py
  - coverage run overwatch-py/tests.py

after_success:
  - codecov