language: python
python:
    - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - pytest overwatch-py/tests.py
  - coverage run overwatch-py/tests.py

after_success:
  - codecov